# Generated by Django 4.2.6 on 2023-12-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disco', models.CharField(max_length=30)),
                ('artista_disco', models.CharField(max_length=30)),
                ('duracion_disco', models.CharField(max_length=30)),
            ],
        ),
    ]
