# Generated by Django 4.2.6 on 2023-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega3', '0002_disco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='duracion_disco',
            field=models.DurationField(),
        ),
    ]
