# Generated by Django 4.2.6 on 2023-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_entrega3', '0005_alter_disco_duracion_disco_alter_temas_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='duracion',
            field=models.ImageField(upload_to=''),
        ),
    ]
